version: '3.8'

services:
  client:
    image: ghcr.io/codefluss/test-nextjs-server
    container_name: test-client
    pull_policy: always
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    restart: always
