version: '3.8'

services:
  client:
    image: ghcr.io/codefluss/test-nextjs-server
    container_name: test-client
    pull_policy: always
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - static_volume:/app/staticfiles
    depends_on:
      - api
      - client
    networks:
      - presence_prod_nw