services:
  client:
    image: ghcr.io/codefluss/test-nextjs-server
    container_name: test-client
    pull_policy: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - test-server-nw

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - client
    networks:
      - test-server-nw

networks:
  test-server-nw:
    external: true

